name: release

on:
  push:
    tags:
      - '*'

jobs:
  build-judger:
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   artifact_name: rurikawa
          #   asset_name: rurikawa-linux-amd64-gnu
          #   # target_name: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            artifact_name: natrium
            artifact_name_2: navm
            asset_name: natrium-linux-amd64-musl
            asset_name_2: navm-linux-amd64-musl
            target_name: x86_64-unknown-linux-musl
          - os: windows-latest
            artifact_name: natrium.exe
            artifact_name_2: navm.exe
            asset_name: natrium-windows-amd64.exe
            asset_name_2: navm-windows-amd64.exe
          - os: macos-latest
            artifact_name: natrium
            artifact_name_2: navm
            asset_name: natrium-macos-amd64
            asset_name_2: navm-macos-amd64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build rust
        if: ${{ matrix.target_name == 0 }}
        run: |
          cargo fetch
          cargo build --frozen --release

      - name: install musl tools
        if: ${{ matrix.target_name == 'x86_64-unknown-linux-musl' }}
        run: sudo apt update && sudo apt install musl musl-dev musl-tools

      - name: Install rust target
        if: ${{ matrix.target_name != 0 }}
        continue-on-error: true
        run: rustup target add ${{ matrix.target_name }}

      - name: Build rust (targeted)
        if: ${{ matrix.target_name != 0 }}
        run: |
          cargo fetch
          cargo build --frozen --release --target ${{ matrix.target_name }}

      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ matrix.target_name != 0 }}
          if_true: target/${{matrix.target_name}}/release
          if_false: target/release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.condval.outputs.value }}/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.condval.outputs.value }}/${{ matrix.artifact_name_2 }}
          asset_name: ${{ matrix.asset_name_2 }}
          tag: ${{ github.ref }}
          overwrite: true
