name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          default: true
      - name: Build
        run: cargo build --verbose --package r0vm
      - name: Run tests
        run: cargo test --verbose --package r0vm
