// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `hello.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

///  argument
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:hello.SayRequest)
pub struct SayRequest {
    // message fields
    ///  data type and position of data
    // @@protoc_insertion_point(field:hello.SayRequest.name)
    pub name: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:hello.SayRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SayRequest {
    fn default() -> &'a SayRequest {
        <SayRequest as ::protobuf::Message>::default_instance()
    }
}

impl SayRequest {
    pub fn new() -> SayRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &SayRequest| { &m.name },
            |m: &mut SayRequest| { &mut m.name },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SayRequest>(
            "SayRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SayRequest {
    const NAME: &'static str = "SayRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SayRequest {
        SayRequest::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SayRequest {
        static instance: SayRequest = SayRequest {
            name: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SayRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SayRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SayRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SayRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  return value
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:hello.SayResponse)
pub struct SayResponse {
    // message fields
    ///  data type and position of data
    // @@protoc_insertion_point(field:hello.SayResponse.message)
    pub message: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:hello.SayResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SayResponse {
    fn default() -> &'a SayResponse {
        <SayResponse as ::protobuf::Message>::default_instance()
    }
}

impl SayResponse {
    pub fn new() -> SayResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "message",
            |m: &SayResponse| { &m.message },
            |m: &mut SayResponse| { &mut m.message },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SayResponse>(
            "SayResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SayResponse {
    const NAME: &'static str = "SayResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.message = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.message.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.message);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.message.is_empty() {
            os.write_string(1, &self.message)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SayResponse {
        SayResponse::new()
    }

    fn clear(&mut self) {
        self.message.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SayResponse {
        static instance: SayResponse = SayResponse {
            message: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SayResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SayResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SayResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SayResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0bhello.proto\x12\x05hello\"\x20\n\nSayRequest\x12\x12\n\x04name\x18\
    \x01\x20\x01(\tR\x04name\"'\n\x0bSayResponse\x12\x18\n\x07message\x18\
    \x01\x20\x01(\tR\x07message2<\n\x0cHelloService\x12,\n\x03say\x12\x11.he\
    llo.SayRequest\x1a\x12.hello.SayResponseJ\xff\x03\n\x06\x12\x04\x01\0\
    \x16\x01\n+\n\x01\x0c\x12\x03\x01\0\x12\x1a!\x20version\x20of\x20protoco\
    l\x20buffer\x20used\n\n:\n\x01\x02\x12\x03\x04\0\x0e\x1a0\x20package\x20\
    name\x20for\x20the\x20buffer\x20will\x20be\x20used\x20later\n\n+\n\x02\
    \x06\0\x12\x04\x07\0\n\x01\x1a\x1f\x20service\x20which\x20can\x20be\x20e\
    xecuted\n\n\n\n\x03\x06\0\x01\x12\x03\x07\x08\x14\n+\n\x04\x06\0\x02\0\
    \x12\x03\t\x04/\x1a\x1e\x20function\x20which\x20can\x20be\x20called\n\n\
    \x0c\n\x05\x06\0\x02\0\x01\x12\x03\t\x08\x0b\n\x0c\n\x05\x06\0\x02\0\x02\
    \x12\x03\t\r\x17\n\x0c\n\x05\x06\0\x02\0\x03\x12\x03\t\"-\n\x16\n\x02\
    \x04\0\x12\x04\r\0\x10\x01\x1a\n\x20argument\n\n\n\n\x03\x04\0\x01\x12\
    \x03\r\x08\x12\n-\n\x04\x04\0\x02\0\x12\x03\x0f\x04\x14\x1a\x20\x20data\
    \x20type\x20and\x20position\x20of\x20data\n\n\x0c\n\x05\x04\0\x02\0\x05\
    \x12\x03\x0f\x04\n\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x0f\x0b\x0f\n\x0c\
    \n\x05\x04\0\x02\0\x03\x12\x03\x0f\x12\x13\n\x1a\n\x02\x04\x01\x12\x04\
    \x13\0\x16\x01\x1a\x0e\x20return\x20value\n\n\n\n\x03\x04\x01\x01\x12\
    \x03\x13\x08\x13\n-\n\x04\x04\x01\x02\0\x12\x03\x15\x04\x17\x1a\x20\x20d\
    ata\x20type\x20and\x20position\x20of\x20data\n\n\x0c\n\x05\x04\x01\x02\0\
    \x05\x12\x03\x15\x04\n\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x15\x0b\x12\
    \n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x15\x15\x16b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(SayRequest::generated_message_descriptor_data());
            messages.push(SayResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
