name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Add rust nightly
        run: rustup update nightly; rustup default nightly;
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
